"""Add passage_ref

Revision ID: e51aec460817
Revises: 2026_07_16_profile_fields
Create Date: 2026-07-17 17:27:10.923244+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e51aec460817'
down_revision: Union[str, None] = '2026_07_16_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('passage_ref', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('answer_placeholder', sa.String(), nullable=True))
    op.alter_column('questions', 'correct_answer',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('questions', 'answer_placeholder')
    op.drop_column('questions', 'passage_ref')
    # ### end Alembic commands ###
