"""Add remaining_time to SubmissionDraft

Revision ID: dec75d462284
Revises: 4acaf9c98c1d
Create Date: 2026-08-18 00:02:55.771002+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec75d462284'
down_revision: Union[str, None] = '4acaf9c98c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_drafts', sa.Column('remaining_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_drafts', 'remaining_time')
    # ### end Alembic commands ###
