"""Add original_question_number

Revision ID: 4acaf9c98c1d
Revises: add_image_url_to_questions
Create Date: 2026-08-15 08:45:45.027064+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acaf9c98c1d'
down_revision: Union[str, None] = 'add_image_url_to_questions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('original_question_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'original_question_number')
    # ### end Alembic commands ###
